#!/usr/bin/env bash
# jobstack 스킬 프리앰블 로케이터 — 생성 파일. 원본은 templates/skill-preamble.sh 이며
# bin/gen-skill-docs.sh 가 각 스킬의 scripts/preamble.sh 로 복제한다(직접 수정 금지).
#
# 역할: 이 스킬 디렉토리가 어디에 설치됐든(저장소 직접, ~/.claude/skills 심링크, 복사,
# 플러그인) 실경로를 따라 올라가 bin/jobstack-preamble 를 찾아 실행한다.
# Claude Code 는 심링크 설치에서 ${CLAUDE_SKILL_DIR} 를 심링크 경로로 치환하므로
# `cd -P` 로 물리 경로를 얻는다(검토 보고서 D-1).
#
# 용법: preamble.sh <skill> [session_id] [plugin_data_dir]
set -u
: "${HOME:=/tmp}"  # $HOME 미설정에서도 죽지 않는다(리뷰 반영)
umask 077          # 상태 트리 개인정보 보호 — bin/jobstack-preamble 과 동일

HERE="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL="${1:-$(basename "$(dirname "$HERE")")}"

FOUND=""
D="$HERE"
for _ in 1 2 3 4 5 6; do
  D="$(dirname "$D")"
  if [ -x "$D/bin/jobstack-preamble" ]; then FOUND="$D/bin/jobstack-preamble"; break; fi
  [ "$D" = "/" ] && break
done
if [ -z "$FOUND" ]; then
  for CAND in "${JOBSTACK_HOME:-}" "${HOME:-}/.claude/skills/jobstack" "/app/skills/jobstack" "/var/jobclaw/skills/jobstack"; do
    [ -n "$CAND" ] && [ -x "$CAND/bin/jobstack-preamble" ] && { FOUND="$CAND/bin/jobstack-preamble"; break; }
  done
fi

if [ -n "$FOUND" ]; then
  exec "$FOUND" "$SKILL" "${2:-}" "${3:-}"
fi

# 폴백 — bin/ 을 찾지 못한 설치(SKILL.md 만 복사된 환경). 최소 컨텍스트만 출력한다.
_JS_STATE="${JOBSTACK_STATE_DIR:-$HOME/.jobstack}"
mkdir -p "$_JS_STATE/analytics" "$_JS_STATE/profiles" "$_JS_STATE/tracker" \
         "$_JS_STATE/company-cache" "$_JS_STATE/interview-history" "$_JS_STATE/sessions" \
         "$_JS_STATE/defense-maps" "$_JS_STATE/job-cache" 2>/dev/null || true
if [ -n "${JOBSTACK_RUNTIME:-}" ]; then RUNTIME="$JOBSTACK_RUNTIME"; elif [ -n "${JOBCLAW_RUN_ID:-}" ]; then RUNTIME="bot"; else RUNTIME="cli"; fi
{
  echo "# generated by skill preamble fallback"
  printf '_JS_STATE=%q\n' "$_JS_STATE"
  printf '_JS_BIN=%q\n' "unresolved"
  printf 'TODAY=%q\n' "$(TZ=Asia/Seoul date +%Y-%m-%d)"
  printf 'JOBSTACK_RUNTIME=%q\n' "$RUNTIME"
} > "$_JS_STATE/env.sh.tmp.$$" 2>/dev/null && mv -f "$_JS_STATE/env.sh.tmp.$$" "$_JS_STATE/env.sh" 2>/dev/null \
  || rm -f "$_JS_STATE/env.sh.tmp.$$" 2>/dev/null || true  # 원자적 교체 — 정상 경로와 동일(리뷰 반영)
echo '<!-- jobstack-preamble fallback -->'
echo '### 실행 컨텍스트'
echo '```text'
echo "SKILL_NAME=$SKILL"
echo "PREAMBLE_FALLBACK=true"
echo "JOBSTACK_RUNTIME=$RUNTIME"
echo "TODAY_KST=$(TZ=Asia/Seoul date +%Y-%m-%d)"
echo "PROACTIVE=true"
echo "ACTIVE_SESSIONS=0"
if [ -f "$_JS_STATE/profiles/default.yaml" ]; then echo "PROFILE_EXISTS=true"; else echo "PROFILE_EXISTS=false"; fi
if [ -f "$_JS_STATE/profiles/experiences.yaml" ]; then echo "EXPERIENCES_EXISTS=true"; else echo "EXPERIENCES_EXISTS=false"; fi
echo "JS_STATE=$_JS_STATE"
echo "JS_BIN=unresolved"
echo "ENV_FILE=$_JS_STATE/env.sh"
if [ -f "$_JS_STATE/env.sh" ]; then echo "STATE_WRITE_FAILED=false"; else echo "STATE_WRITE_FAILED=true"; fi
echo '```'
echo "주의: jobstack 의 bin/ 디렉토리를 찾지 못했습니다(스킬 디렉토리만 복사된 설치). 스크립트 호출(\`jobstack-view\`, \`fetch-jobs.mjs\` 등)이 필요한 단계는 건너뛰고, 필요한 자료는 사용자에게 요청하세요."
exit 0
